ci: Workaround for bundler permission issue
```
+ brew test --verbose taiki-e/test/cargo-hack
Fetching gem metadata from https://rubygems.org/.......
Fetching public_suffix 7.0.0
Fetching base64 0.3.0
Fetching bindata 2.5.1
Fetching concurrent-ruby 1.3.5
Installing base64 0.3.0
Fetching logger 1.7.0
Installing bindata 2.5.1
Fetching minitest 5.27.0
Installing public_suffix 7.0.0
Fetching plist 3.7.2
Installing logger 1.7.0
Installing plist 3.7.2
Fetching ruby-macho 4.1.0
Fetching sorbet-runtime 0.6.12845
Installing minitest 5.27.0
Installing concurrent-ruby 1.3.5
Fetching warning 1.5.0
Installing ruby-macho 4.1.0
Installing sorbet-runtime 0.6.12845
Installing warning 1.5.0
Bundler cannot reinstall base64-0.3.0 because there's a previous installation of
it at
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/base64-0.3.0
that is unsafe to remove.
The parent of
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems/base64-0.3.0
is world-writable and does not have the sticky bit set, making it insecure to
remove due to potential vulnerabilities.
Please change the permissions of
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.4.0/gems
or choose a different install path.
Error: failed to run `/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/3.4.8/bin/bundle install`!
```